import{S as u,i as d}from"./assets/vendor-B07T6_gy.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const m={key:"48326966-0a5fa166f497e375098be0f90",image_type:"photo",orientation:"horizontal",safesearch:"true"},f=a=>{const e=new URLSearchParams({...m,q:a});return fetch(`https://pixabay.com/api/?${e}`)},h=a=>a.hits.map(e=>`<li class='gallery-item'>
            <a href='${e.largeImageURL}'><img class='gallery-img' src='${e.webformatURL}' alt='${e.tags}'></a>
            <ul class='user-activity'>
                <li class='user-activity-item'><span class='user-activity-header'>Likes</span>${e.likes}</li>
                <li class='user-activity-item'><span class='user-activity-header'>Views</span>${e.views}</li>
                <li class='user-activity-item'><span class='user-activity-header'>Comments</span>${e.comments}</li>
                <li class='user-activity-item'><span class='user-activity-header'>Downloads</span>${e.downloads}</li>
            </ul>
        </li>`),l=document.querySelector(".search-form"),n=document.querySelector(".gallery"),c=document.querySelector(".loader"),y=new u(".gallery a",{captionsData:"alt"}),p=a=>{d.error({title:"",message:a,position:"topRight"})},g=a=>{a.preventDefault();const e=l.query.value;n.innerHTML="",c.classList.remove("hidden-loader"),f(e).then(r=>{if(!r.ok)throw new Error(r.status);return r.json()}).then(r=>h(r)).then(r=>{if(r.length>0)n.innerHTML=r.join(""),y.refresh();else throw new Error("Sorry, there are no images matching your search query. Please try again!")}).catch(r=>p(r.message)).finally(()=>c.classList.add("hidden-loader"))};l.addEventListener("submit",g);
//# sourceMappingURL=index.js.map
